### ISSUE TITLE
Linux: asks for password on first launch

### ISSUE THREAD

**Issue by hkdb** [mysteriumnetwork/mysterium-vpn-desktop#117]
Hi there... I noticed that on first launch, the app asks for your password in the form of what looks like pkexec without giving a whole lot of information except that it's trying to run a bash command. This only happens on the first time I install and launch the app. It no longer asks for it even if I purge the app, remove the .mysterium directory and re-install it. Can someone shed some light on what that's trying to do and how the password is handled? Thanks.

![Screenshot from 2021-05-19 05-48-10](https://user-images.githubusercontent.com/38838639/118815418-14cbaf00-b866-11eb-8038-4fdbe1a7e024.png)

**Comment by hkdb** [comment]
Actually to clarify one thing from the above, it turns out that there are still some processes running even after I purged the package. So if I kill the processes or reboot after purging the package and then reinstall the package, it will ask for that password again.

My question from the above comment still stands though. Any further details would be very much appreciated. Thanks!

**Comment by chompomonim** [comment]
To establish VPN tunnel, we need to run process under root permissions. There is service called `mysterium-supervisor`, it is always running in background and is ready to run main myst process when needed (when app is active). You see this authentication request each time supervisor is starting (because it needs to run in root process). 

P.S. It is better to ask such questions in out discord channel (https://discordapp.com/invite/n3vtSwc)
