### ISSUE TITLE
409 from Pilvytis when Topping Up

### ISSUE THREAD

**Issue by yue-dongchen** [mysteriumnetwork/mysterium-vpn-desktop#142]
When creating a payment with the top-up dialogue, an error message, "something went wrong", appears. The logs show it as a 500 error.

[2021-06-20 19:43:56.810] [error] Could not create a payment order Request failed with status code 500 (path="/identities/`my identity`/payment-order")

I then tried directly making the post request to the Tequila API in order to get some more verbose information, which indicated that Pilvytis couldn't carry out the request:
```
{
    "message": "server response invalid: 409 Conflict (https://testnet2-pilvytis.mysterium.network/api/v1/payment/orders){\"error\":\"identity is offchain\",\"field\":\"identity\"}"
}
```
Since I'd just discovered Mysterium today and am unfamiliar with cryptocurrencies (quite confused at the moment - I read somewhere that Pilvytis V1 doesn't support off-chain transactions), I can't look into it any further. Help would be greatly appreciated.

**Comment by tadaskay** [comment]
Hello! Since testnet chain (goerli) is under heavy load at the moment, we have temporarily disabled identity blockchain registrations to prevent issues. We're getting ready for a new testnet release soon, where issues like this should not occur.
Meanwhile, we have increased amount of free MYSTT you get with a new identity so you should never run out of balance.
