### ISSUE TITLE
MYST topup not working [bug]

### ISSUE THREAD

**Issue by kharthigeyan** [mysteriumnetwork/mysterium-vpn-desktop#160]
**Describe the bug**
I tried to top-up for MYST using USDT.

**To Reproduce**
1. Go to Wallet
2. Click Top-up
3. Select Currency USDT
4. Type the amount
5. Click the Start payment button
6. Send money to the mentioned address, example: 0x4ed540922e00f7A63f5D8010912c9fCe9810Ce85
7. MYSTT receiving address: 0xD1Ad406d7D1492b3bEa2648bb432f9611415496b

**Expected behavior**
My wallet balance should increase to the amount which I bought.

**Logs**
Attach app logs  [main.log](https://github.com/mysteriumnetwork/mysterium-vpn-desktop/files/6825208/main.log)
[renderer.log](https://github.com/mysteriumnetwork/mysterium-vpn-desktop/files/6825209/renderer.log)

**Screenshots**
![image](https://user-images.githubusercontent.com/8716763/125935738-2f39bb1a-7f2d-4feb-96ba-b6e0dcb3b4ed.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Mac OS ]
 - App Version [e.g. 4.2.1]

**Additional context**
Did not receive the Top-up amount.

**Comment by tadaskay** [comment]
Hi, could you attach all the logs to the issue?

> Attach logs (app, node, supervisor) to the issue. Where to find the logs: https://github.com/mysteriumnetwork/mysterium-vpn-desktop#logging

**Comment by tadaskay** [comment]
Thanks for reporting! We're investigating the case at the moment.

**Comment by tomasmik** [comment]
Hi there, sorry for the trouble. It seems that from all the transfers we've made, this one failed because of some sync error on the blockchain. Since then we've made some changes to try and address these issues.

I see that the money did eventually reach you, it was just a lot slower than usual. You're address is reporting 50+ MYST and here is the transfer made: https://goerli.etherscan.io/tx/0x7b7882be8fb1aa67abcad3eac0ca5114599df9f4eb2a0ba3bb158631a013b7e3

There transfer was made for identity: `0x245D08Ba2c6c805981e7A488B79Ff2092329E2E5`. If you did not change your identity, the funds should be there for at least 3 days now. If that's not the case feel tree top open the issue back. Sorry for any trouble caused.
