### ISSUE TITLE
[bug Installed Mysterium on second computer (linux) goes straight to top up wallet which is already topped up on other computer, bypasses any login.  Give us more money????

### ISSUE THREAD

**Issue by eobf737** [mysteriumnetwork/mysterium-vpn-desktop#333]
**Describe the bug**

**To Reproduce**
3. See error

**Expected behavior**

**Logs**
Attach logs (app, node, supervisor) to the issue. Where to find the logs: https://github.com/mysteriumnetwork/mysterium-vpn-desktop#logs

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - App Version [e.g. 4.1.0]

**Additional context**

**Comment by kiraitachi** [comment]
Even though your bug description body is empty, and this filed issue "is quite a mess" I believe I understood your issue.

Did you import in the second computer the Mysterium Keystore.json that you should've exported from the first computer? So that the same identity and wallet is used, and you can have the MYST that you top-up in your first computer in the second.

![image](https://user-images.githubusercontent.com/40744673/163038054-caac62ce-a717-463b-8ce9-87242573fa1b.png)

You go to Settings>Mysterium ID and then Backup option as in the picture. Then import that keystore.json on your second computer.
