### ISSUE TITLE
[bug] Unable to connect on linux

### ISSUE THREAD

**Issue by ChromiumCat0** [mysteriumnetwork/mysterium-vpn-desktop#408]
**Describe the bug**
I can't connect to any mysterium nodes. Error message is `Failed to connect: could not start new connection: failed to start connection endpoint: could not configure device: failed to create wg interface: failed to create TUN device myst0: no such device`

**To Reproduce**
1. Choose any node/country
2. Try to connect

**Expected behavior**
Connection works

**Logs**
[supervisor](https://files.chromium.hu/!S95SGZ8uUP/myst_supervisor.log)
[application](https://files.chromium.hu/!Z8XZyuBJJj/main.log)

**Screenshots**
https://prnt.sc/3WYSkwCt8-zh

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - App Version: 10.13.3

**Additional context**
Running GNOME 42.4, NetworkManager 1.40.2-1, wpa_supplicant v2.10

**Comment by isaackielma** [comment]
From our docs: "There can be various issues regarding the TUN device depending on your host environment. This usually means you do not have the tun kernel module. Properly loading the module on your host should do the trick, otherwise you might have to re-compile your Kernel with the tun module."

Could you please try going over these docs guide: https://docs.mysterium.network/troubleshooting/tun-device-errors

Please let us know in case issue persists.

**Comment by ChromiumCat0** [comment]
The issue no longer persist, although I don't know how I fixed it.
