### ISSUE TITLE
App fails to auto update latest version

### ISSUE THREAD

**Issue by isaackielma** [mysteriumnetwork/mysterium-vpn-desktop#419]
**Describe the bug**
Users on the earlier version of the app 10.13.3 are experiencing app stuck on starting mode, unable to auto update to latest version 10.14.2 automatically.

**To Reproduce**
1. Go to 'earlier version of app'
2. Click on app to launch it
3. See Download update error

**Expected behavior**
Update should download automatically as suggested in loading app screen

**Logs**
Attach logs (app, node, supervisor) to the issue. Where to find the logs: https://github.com/mysteriumnetwork/mysterium-vpn-desktop#logs

**Screenshots**
<img width="913" alt="Screenshot 2022-12-07 at 10 05 43" src="https://user-images.githubusercontent.com/84313603/206193331-2859d587-d410-4ca5-81d7-0d0124ef6b28.png">

**Desktop (please complete the following information):**
 - OS: Desktop OSs
 - App Version: Latest

**Additional context**
Solution to this issue is to ask users to manually download new version:

"Please download newest app version manually instead, it should work then:https://github.com/mysteriumnetwork/mysterium-vpn-desktop/releases/"

**Comment by gir489returns** [comment]
I've been having this issue since yesterday. The Mysterium devs are awful at fixing stuff like this. There was a time where they deployed a build to production that stopped all Windows users from using the VPN and they didn't resolve it for days.

Anyway, what I've been doing since yesterday is just launching the client with -no-update, which I found digging around the source. https://github.com/mysteriumnetwork/mysterium-vpn-desktop/blob/c94ff3692dfd115b131dc74a301d647995949b96/src/main/index.tsx#L249

Once you do that, you can launch the client.

**Comment by DROPLOTHUB** [comment]
fix is just download the latest from GitHub

this is the issue their having right now 

![Capture](https://user-images.githubusercontent.com/72875833/206346767-88981368-a9cc-4d8e-bada-85e91c40a035.PNG)

**Comment by hkup859** [comment]
@isaackielma Hi, I'm not a Mysterium developer, but I'm a software developer and know the language it's written in. I attempted to replicate your issue by downloading the 10.13.3, however it worked properly for me. It said there was an update, downloaded it, told me to restart, then after a weird issue where it wasn't letting me restart, it seemed to be working properly (following a successful restart). After that it was asking me for my password to install a helper utility.

I am on MacOS Ventura Version 13.0.1. I have never used the Mysterium VPN before, but downloaded it in order to try and test this.

To help me better diagnose the issue, can you please provide a few more details:
* What is your OS? What version of your OS do you have?
* Have you updated the VPN before or is this the first time? If you have done it before, did it previously work (give as much detail as you can remember)?
* Can you attach some logs? Remember to sanitize sensitive info.
* What is the exact error you receive (screenshot if available please)?

Again, I am not a Mysterium developer and I can make no promises, but I will try to help out if I can, thank you.

**Comment by marconovino** [comment]
having the same issue myself! will try github build!
