### ISSUE TITLE
Killswitch for dVPN desktop app

### ISSUE THREAD

**Issue by HeroHann** [mysteriumnetwork/mysterium-vpn-desktop#47]
I have used the VPN in the last days. hough after each 10 GB it seems to close the connection. As there is no kill switch this is pretty bad.

Is there a kill switch? And if not, will it be implemented? It is really necessary!

**Comment by chompomonim** [comment]
This is quite high in our planned features list. There are some issues on Windows platform that are stopping us from releasing it right now.

**Comment by HeroHann** [comment]
Well without a kill switch a VPN is more or less useless!
Any update on it? Maybe first release it on Mac if it is working there?.

**Comment by chompomonim** [comment]
There are many usecases when VPN is useful even without kill switch. But the good news is that we started looking on it. First release will be for Windows (it is much more popular platform that macOS).

**Comment by HeroHann** [comment]
Well not for people looking for security and privacy as each time the VPN disconnects it is lost...

Any ETA on the feature?

**Comment by cvl** [comment]
Yes

**Comment by youssefya7** [comment]
Any updates regarding the Killswitch guys?

**Comment by AnuxX** [comment]
Please add a kill switch to the linux client, you are the only one who supports dvpn on linux, I think you underestimate the danger of not having a kill switch
Not having a kill switch defeats the purpose of Mysterium
In the dvpn system, this is especially critical because the owner of the "server" can turn it off at any time, which happens much more often than with normal vpn.
And at that moment:
Your ISP will see the site you are visiting.
The site will see your IP address (and possibly your location)
You'll be vulnerable to MITM hacker attacks.
After that point, all the privacy that many people use mysterium for is lost.
They pay money for it and don't get that simple and critical function that any other vpn client has.
This is the most critical Mysterium vulnerability and you have not fixed it for a year.
