### ISSUE TITLE
Multi-Hopping Question

### ISSUE THREAD

**Issue by danrobi11** [mysteriumnetwork/mysterium-vpn-desktop#69]
Hi, someone posted [this](https://old.reddit.com/r/thehatedone/comments/jeqpez/wondering_if_i_can_present_to_you_mysterium/) in Reddit. Im having hard time to find anything related with multi-hopping. Is it 2/3 hops by default? Can we config multi-hopping? Plz make it easy to find in F.A.Q maybe, idk. Thanks!

**Comment by chompomonim** [comment]
Mysterium don't have multi-hop solution at them moment. We're focusing on anti-censorship and privacy rather than on anonymity. 

We have some kind of multihop solution in mind, but it is more related to mixing exit nodes during same session (one services could use one exit IP, while other would use another one, all done automatically). But this is due for streaming unlocking you would need different kind IP that for torrenting or wikipedia browsing. 

Also it is better to ask question in our Discord: discordapp.com/invite/n3vtSwc
